name: FujiNet PlatformIO CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [ATARI]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS : true

    steps:
    - uses: actions/checkout@v2
 
