name: FujiNet PlatformIO CI

on:
  push:
    branches:
      - release
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [ATARI]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
          
    - name: Discord notification 1
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "testDeploy"
        description: "Build and deploy Test"
        color: 0x0000ff
        username: R2D2
     
    - name: Run the GitHub Actions Status Embed Action
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: '1234567890'
        webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
