name: FujiNet PlatformIO CI

on:
  push:
    branches:
      - release
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [ATARI]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
     
    - name: Discord 2    
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
     
    - name: Discord 2
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: '1234567890'
        webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
